<a href="https://colab.research.google.com/github/ArshockAbedan/ML2021/blob/main/NLP_word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restaurant",30)

[27, 19]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[7, 29], [27, 19], [2, 4], [8, 8, 20], [3, 4, 15], [9, 29], [14, 4, 2], [9, 29], [9, 15], [22, 8]]


In [6]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 7 29  0  0]
 [27 19  0  0]
 [ 2  4  0  0]
 [ 8  8 20  0]
 [ 3  4 15  0]
 [ 9 29  0  0]
 [14  4  2  0]
 [ 9 29  0  0]
 [ 9 15  0  0]
 [22  8  0  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 193ms/step - loss: 0.6380 - accuracy: 0.9000


0.8999999761581421

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]

array([ 0.0222795 , -0.01296081, -0.03212159,  0.0127831 , -0.04933119],
      dtype=float32)

In [14]:
weights[4]

array([-0.02651966,  0.01967602, -0.04950726,  0.07934188, -0.03609801],
      dtype=float32)

In [15]:
weights[16]

array([ 0.01088827, -0.00435676,  0.03907354,  0.03403531,  0.01679373],
      dtype=float32)